#!/usr/bin/env bash

# This script displays information about subdomains of a given domain.


display_info() {
    domain=$1
    subdomain=$2
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

get_subdomain_info() {
    domain=$1
    subdomain=$2
    dig_result=$(dig +short "$subdomain.$domain")
    if [[ -n $dig_result ]]; then
        record_type=$(dig +short "$subdomain.$domain" | awk 'NR==1{print $1}')
        destination=$(dig +short "$subdomain.$domain")
        display_info "$domain" "$subdomain"
    fi
}

display_default_info() {
    domain=$1
    get_subdomain_info "$domain" www
    get_subdomain_info "$domain" lb-01
    get_subdomain_info "$domain" web-01
    get_subdomain_info "$domain" web-02
}

main() {
    domain=$1
    subdomain=$2

    if [[ -z $subdomain ]]; then
        display_default_info "$domain"
    else
        get_subdomain_info "$domain" "$subdomain"
    fi
}

main "$@"
