#!/usr/bin/env bash
# Configure Nginx server to listen to port 80

# Remove the default configuration file
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to enable the default configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx service
service nginx restart
