#!/usr/bin/env bash
#  script that loops from 1 to 10 and:displays bad luck for the 4th loop iteration, displays good luck for the 8th loop iteration, displays Best School for the other iterations

while ((i <= 9)); do 
    if ((i == 3)); then
        echo "Bad Luck"
    elif ((i == 7)); then
        echo "Good Luck"
    else
        echo "Best School"
    fi
    ((i++))
done
