#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes

i=0
hour=0
while [ $hour -lt 13 ]; do
    echo "Hour: $hour"
	while [ $i -lt 60 ]; do
    	echo "$i"
		((i++))
	done
        ((hour++))
		i=0
done